### ISSUE TITLE
やることリスト

### ISSUE THREAD

**Issue by AyaEbata** [AyaEbata/nantokaApp#1]
- [x] マイナスいかないようにする
- [x] 右上のmenuに全部消すやつ作る
- [x] SDK 21と23入れる
- [x] 後、プラスボタンと戻るボタンの位置入れ替えたいな
- [x] GUIで画面つくる！（やっと表示されたから追加！

**Comment by Tecco** [comment]
### SDK 21と23入れる -> GUIレイアウト使えたらいいね

**Comment by AyaEbata** [comment]
@Tecco 
SDK 21と23入れたお
そしたら何故か22も使えるようになた

てか、23だけメニューのとこの青いやつが暗めの青になる
くまったくまった

**Comment by Tecco** [comment]
> てか、23だけメニューのとこの青いやつが暗めの青になる

多分それはしゃーないから、とりあえず無視しよう
次はD&Dでレイアウト画面を作ってみよう

**Comment by Tecco** [comment]
- Developでブランチ切って、プルリク作ろう

**Comment by AyaEbata** [comment]
@Tecco 
developブランチ切った運用したことないんだが
git flow？？

**Comment by Tecco** [comment]
@AyaEbata 
まーfeatureとかまでやりたいなら。
developだけ作って、キリ良いとこでmasterにマージする感じでいいんでないかい。

`git checkout -b develop`

**Comment by AyaEbata** [comment]
@Tecco 
そゆことか
理解した

**Comment by AyaEbata** [comment]
いちお、PR #2 で対応し終わった(*'ω'*)

**Comment by AyaEbata** [comment]
PR #2 をマージしたのでこっちもcloseしますー。

**Comment by AyaEbata** [comment]
closed #1

**Comment by AyaEbata** [comment]
Closed #1.

**Comment by AyaEbata** [comment]
PR #2 をマージしたのでこっちもcloseしますー。
