### ISSUE TITLE
初期起動したときに一瞬でるあの画面導入してみたい

### ISSUE THREAD

**Issue by AyaEbata** [AyaEbata/nantokaApp#11]
（Java全然書いてないな、このアプリ

**Comment by Tecco** [comment]
@AyaEbata 
Androidでは推奨されていません。
Android的にJavaは書かなければ書かないほど良いです(リソースに任せる

**Comment by AyaEbata** [comment]
@Tecco 
なんでなの？！Σ
なんかいきなり起動されるとかさみしーじゃん←

ほえー
書かない方がいいのかー

**Comment by Tecco** [comment]
@AyaEbata 
http://qiita.com/glayash/items/646e5c0d5de82cfc17bc

**Comment by AyaEbata** [comment]
（なんでなの聞く前にもうちっと調べようとおもた。Wi-Fiとスマホの速度制限がきついかもしんないけど。今後そうしよう。

**Comment by Tecco** [comment]
ggrks

**Comment by AyaEbata** [comment]
@Tecco
すんません

ぐーぐる先生 < @Tecco先生

ということで

**Comment by AyaEbata** [comment]
スプラッシュ画面って初期表示のなんか処理してる間に表示するための画面だったのか←
どこもいれてたから、アプリにはあるべきものだと思ってました←

というわけで、必要ないのでcloseします。
