### ISSUE TITLE
ボタン変えたい

### ISSUE THREAD

**Issue by AyaEbata** [AyaEbata/nantokaApp#6]
右下の戻るボタン、やっぱりマイナスボタンにしたい

戻るボタン気持ち悪い

**Comment by Tecco** [comment]
https://www.iconfinder.com/search/?q=minus&price=free

**Comment by AyaEbata** [comment]
https://www.iconfinder.com/icons/211774/minus_outline_icon#size=256

これにしよう。
サイズとか拡張子とかなんたらについて迷い中。

**Comment by AyaEbata** [comment]
ああ。
このサイトの上に出ているのはもしやshow sizeだからこの画面上で表示されるサイズのことなのかなんなのか。

**Comment by AyaEbata** [comment]
なんかエラーになった てへぺろ

**Comment by AyaEbata** [comment]
でけたからcloseする(_'ω'_)
