### ISSUE TITLE
レイアウト上に出ている警告について

### ISSUE THREAD

**Issue by AyaEbata** [AyaEbata/nantokaApp#8]
警告をクリックすると警告消えるが、何が変更されて警告消えたのか気になる。
目で見た感じ変わったところみつかんなかった。

<img width="760" alt="2016-03-27 13 10 10" src="https://cloud.githubusercontent.com/assets/11349412/14063849/60987716-f420-11e5-9693-681e4b92af21.png">

**Comment by Tecco** [comment]
英語を読めばそのままの意味じゃまいか

**Comment by AyaEbata** [comment]
@Tecco 

（読めない）

**Comment by Tecco** [comment]
layout_marginEnd使った方がええで
ってこと。
Google翻訳するか、そのメッセージをそのままググれば大体でる。
ただし、marginEnd使ったら、API 17以上やからmin SDK関係で使えないはず。
つまり、今回のケースでは無視やな

**Comment by AyaEbata** [comment]
おお。さんくす。

Google翻訳意味わからん訳されやした←
そのままぐくったら、速度制限であれでした←

無視か。

**Comment by AyaEbata** [comment]
@Tecco 
`layout_marginEnd`はPropertiesのlayout:marginにはないの？？

**Comment by Tecco** [comment]
@AyaEbata 
みてなかた。

ないかもな(Android Studio2.0ならあるかも
xmlで直で書いてけば、補完でるはず。
多分、今回のケースで言うとlayout_right残して、layout_marginEnd追加すればおｋなはず。

**Comment by AyaEbata** [comment]
@Tecco 
これについても聞けばよかったー。
とりあえず、marginRightのやつと同じ値のmarginEndを追加してあげたら、警告消えました。 #10

でも、なんで、marginRight残してmarginEndを追加すればいいよってなったのか知りたかったー。

**Comment by Tecco** [comment]
@AyaEbata 
deprecatedなのでmarginEndを使えば良いのだが、昔のOSでは使えないので、marginRightを残さなければならないのだな。

**Comment by AyaEbata** [comment]
@Tecco 
marginRight ＝ marginEnd
っていう認識？

それとも
marginRight ≒ marginEnd？？

それは両方いれたとして、どっちも動くことはないものなの？？
足されて倍になるとかとか。

**Comment by Tecco** [comment]
@AyaEbata 
同じではないです。
例えば、右から左に流れてくレイアウトを実装した際は、startとendが逆になる(はず
基本的にはどっちも書いといても片方しか見にいかない(はず

**Comment by AyaEbata** [comment]
ほえー
なんか、気に食わないｗｗｗｗ

Android Studioには`layout_marginRight`しか選択できないのに警告とかなんなのｗｗｗｗ

まぁでも雰囲気は理解しました。
